version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "../backend/"
    schedule:
      interval: "daily"
      time: "04:30"
    labels:
      - "java"
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "../frontend/"
    schedule:
      interval: "daily"
      time: "04:30"
    labels:
      - "javascript"
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:30"
    labels:
      - "github-actions"
      - "dependencies"
      - "dependabot"
    reviewers:
      - "sumanmaity1234"
    open-pull-requests-limit: 20

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:30"
    labels:
      - "docker"
      - "dependencies"
      - "dependabot"
    reviewers:
      - "sumanmaity1234"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 20
