# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration
#
# Lines starting with "#" are comments.
# Configuration options are organized into tables and keys.
# See documentation for more information on available options.

[changelog]

header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
# template for the changelog body
# https://tera.netlify.app/docs
body = """
{% if version %}\
    ## [{{ version }}](https://github.com/otto-de/gitactionboard/compare/{{ previous.version }}...{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/otto-de/gitactionboard/commit/{{ commit.id }}))
    {% endfor %}
{% endfor %}\n
"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
   { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/otto-de/gitactionboard/issues/${2}))"}, # replace issue numbers
   { pattern = '\sgithub\s', replace = " GitHub "},
   { pattern = '(CVE-[0-9]+-[0-9]+)', replace = "[${1}](https://nvd.nist.gov/vuln/detail/${1})"},
]

commit_parsers = [
  { message = ".*CVE|.*cve|.*security", body = ".*CVE|.*cve|.*security", group = "<!-- 3 -->🛡️ Security" },
  { message = "^(feat|fix|perf|refactor|chore)!", group = "<!-- 0 -->⚠ BREAKING CHANGES" },
  { message = "^feat", group = "<!-- 1 -->⛰️ Features" },
  { message = "^fix", group = "<!-- 2 -->🐛 Bug Fixes" },
  { message = "^doc", group = "<!-- 99 -->📚 Documentation" },
  { message = "^perf", group = "<!-- 5 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 4 -->🚜 Refactor" },
  { message = "^style", group = "<!-- 6 -->🎨 Styling" },
  { message = "^test", group = "<!-- 7 -->🧪 Testing" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore.*\\/backend", skip = true },
  { message = "^chore.*\\/frontend", skip = true },
  { message = "^chore.*talisman.*warnings", skip = true },
  { message = "^chore", group = "<!-- 8 -->⚙️ Miscellaneous Tasks" },
  { message = "^build", group = "<!-- 9 -->👷 Build" },
]

protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
skip_tags = "v0.1.0-beta.1"
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
